In [1]:
import numpy as np
import tensorflow as tf

In [2]:
sentences = [
    'I love my dog',
    'I love my cat',
    'I love my cat and dog',
    'I like to code'
]

In [13]:
vectorization_layer = tf.keras.layers.TextVectorization() 
# can use ragged=True so you can tell that tensors can potentially have different shapes

In [14]:
vectorization_layer.adapt(sentences)
vocabulary = vectorization_layer.get_vocabulary()
print(vocabulary,"\n")
dataset = tf.data.Dataset.from_tensor_slices(sentences)
for i in enumerate(dataset):
    print(i)
sequences = dataset.map(vectorization_layer)
print()
for sentence, sequence in zip(sentences,sequences):
    print(f'{sentence} -----> {sequence}')

['', '[UNK]', np.str_('i'), np.str_('my'), np.str_('love'), np.str_('dog'), np.str_('cat'), np.str_('to'), np.str_('like'), np.str_('code'), np.str_('and')] 

(0, <tf.Tensor: shape=(), dtype=string, numpy=b'I love my dog'>)
(1, <tf.Tensor: shape=(), dtype=string, numpy=b'I love my cat'>)
(2, <tf.Tensor: shape=(), dtype=string, numpy=b'I love my cat and dog'>)
(3, <tf.Tensor: shape=(), dtype=string, numpy=b'I like to code'>)

I love my dog -----> [2 4 3 5]
I love my cat -----> [2 4 3 6]
I love my cat and dog -----> [ 2  4  3  6 10  5]
I like to code -----> [2 8 7 9]


In [15]:
sentence_pre_pad = tf.keras.utils.pad_sequences(sequences,padding='pre')
print(sentence_pre_pad)

[[ 0  0  2  4  3  5]
 [ 0  0  2  4  3  6]
 [ 2  4  3  6 10  5]
 [ 0  0  2  8  7  9]]


In [16]:
test_data  = [
    "I really love my dog",
    "I hate my cat",
    "My dog eats pedegree"
]

In [ ]:
test_seq = vectorization_layer(test_data)
print(vectorization_layer.get_vocabulary())
print(test_seq)

['', '[UNK]', np.str_('i'), np.str_('my'), np.str_('love'), np.str_('dog'), np.str_('cat'), np.str_('to'), np.str_('like'), np.str_('code'), np.str_('and')]
tf.Tensor(
[[2 1 4 3 5]
 [2 1 3 6 0]
 [3 5 1 1 0]], shape=(3, 5), dtype=int64)
