In [49]:
import tensorflow as tf

In [50]:
import numpy as np

In [51]:
dataset = tf.data.Dataset.range(10)
print(dataset)

<_RangeDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>


In [52]:
dataset = dataset.window(5,shift=1, drop_remainder= True)

In [53]:
for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(),end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [54]:
dataset = dataset.flat_map(lambda window: window.batch(5)) 

In [55]:
for window in dataset:
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [56]:
dataset = dataset.map(lambda window: (window[:-1],window[-1]))

In [57]:
for x,y in dataset:
    print(x.numpy(),y.numpy())

[0 1 2 3] 4
[1 2 3 4] 5
[2 3 4 5] 6
[3 4 5 6] 7
[4 5 6 7] 8
[5 6 7 8] 9


In [58]:
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
    print(x.numpy(),y.numpy())

[5 6 7 8] 9
[1 2 3 4] 5
[4 5 6 7] 8
[0 1 2 3] 4
[3 4 5 6] 7
[2 3 4 5] 6


In [59]:
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
    print('x =', x.numpy())
    print('y =', y.numpy())

x = [[1 2 3 4]
 [5 6 7 8]]
y = [5 9]
x = [[2 3 4 5]
 [0 1 2 3]]
y = [6 4]
x = [[4 5 6 7]
 [3 4 5 6]]
y = [8 7]
